CREATE TYPE "public"."escrow_claim_status" AS ENUM('pending', 'verified', 'processing', 'approved', 'disbursed', 'rejected', 'expired');--> statement-breakpoint
CREATE TABLE "escrow_claims" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"claim_code" varchar(20) NOT NULL,
	"pin" varchar(10) NOT NULL,
	"first_name" varchar(100) NOT NULL,
	"last_name" varchar(100) NOT NULL,
	"phone" varchar(20),
	"email" varchar(255),
	"ssn_last_4" varchar(4),
	"date_of_birth" varchar(10),
	"address" varchar(255),
	"city" varchar(100),
	"state" varchar(50),
	"zip_code" varchar(10),
	"escrow_amount_cents" integer NOT NULL,
	"release_fee_cents" integer DEFAULT 0,
	"escrow_type" varchar(100) DEFAULT 'federal_reserve',
	"escrow_description" text,
	"originating_entity" varchar(255),
	"status" "escrow_claim_status" DEFAULT 'pending' NOT NULL,
	"verified_at" timestamp,
	"approved_at" timestamp,
	"disbursed_at" timestamp,
	"disbursement_method" varchar(50),
	"bank_routing_number" varchar(20),
	"bank_account_number" varchar(30),
	"bank_account_type" varchar(20),
	"last_call_at" timestamp,
	"total_calls" integer DEFAULT 0,
	"failed_verification_attempts" integer DEFAULT 0,
	"is_locked" boolean DEFAULT false,
	"notes" text,
	"metadata" jsonb DEFAULT '{}'::jsonb,
	"expires_at" timestamp,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "escrow_claims_claim_code_unique" UNIQUE("claim_code")
);
